//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveySite
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicSurvey
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> Q1Answer { get; set; }
        public Nullable<int> Q2Answer { get; set; }
        public Nullable<int> Q3Answer { get; set; }
        public Nullable<int> Q4Answer { get; set; }
        public Nullable<int> Q5Answer { get; set; }
        public Nullable<int> Q6Answer { get; set; }
        public Nullable<int> Q7Answer { get; set; }
        public Nullable<int> Q8Answer { get; set; }
        public Nullable<int> Q9Answer { get; set; }
        public Nullable<int> Q10Answer { get; set; }
    }
}
